### PR TITLE
Allow broader range of names for user-defined scannos folder

### PR DESCRIPTION
**Pull request by windymilla**
Due to `scannos` being a folder directly under the release (as opposed to
an executable in a subfolder of `tools`, like most of the other settings that
are configurable using `Set File Paths`, there are limitations on the name
a user can choose for their own customised scannos folder.

Previously, the user could not choose a folder name that ended in `scannos`,
e.g. `custom_scannos`, or the next time GG was run, the program reset it to
the default location under the release. The name `scannos_custom` was OK.

Slight adjustment to code now allows names like `custom_scannos`, or
`myscannos`. The only name that does not work is precisely `scannos`, since
it would be hard to know if that was under a release or not.

The manual already described the previous restriction and will be edited to
reflect the new, lesser restriction.

### CODE REVIEW

**Review by cpeel — APPROVED** [review]

**Comment by srjfoo** [comment]
In testing, I obviously didn't know what I was doing. I think I was expecting GG to create the folder instead of having already created it. So it didn't work as expected. I finally spotted the "Locate Scannos" button and clicked on it ... then realized that the folder had to be pre-existing. I was able to quit GG, and this time used the `--home ggdata` and created a `custom-scannos` directory within it. The following is a screenshot showing the dialog and the error window and the file paths list. I can change focus to the main GG window and quit, but the cancel button doesn't work and choosing `custom-scannos` and "Open" doesn't work.

Am I doing something wrong that would be obvious to a regular GG user (I didn't take the time to go read the documentation).

Error messages:

> 
> 20:56:07: Using home directory: /Users/sharonjoiner/ggdata
> 20:56:12: Guiguts 1.4.0: If you have any problems, please include any error messages that appear here with your bug report.
> 20:57:21: Tk::Error: Can't set -mustexist to `1' for Tk::FBox=HASH(0x12082eba0): Can't set -mustexist to `1' for Tk::IconList=HASH(0x117dc4910): unknown option "-mustexist" at /opt/homebrew/Cellar/perl/5.34.0/lib/perl5/site_perl/5.34.0/darwin-thread-multi-2level/Tk/Configure.pm line 45.
>  at /opt/homebrew/Cellar/perl/5.34.0/lib/perl5/site_perl/5.34.0/darwin-thread-multi-2level/Tk/Derived.pm line 294.
> 
> 
>  at /opt/homebrew/Cellar/perl/5.34.0/lib/perl5/site_perl/5.34.0/darwin-thread-multi-2level/Tk/Derived.pm line 306.
>  Tk callback for .fbox.frame
>  Tk callback for .fbox.frame1
>  Tk callback for .fbox.frame2
>  Tk callback for .fbox
>  Tk callback for .fbox.iconlist
>  Tk::Derived::configure at /opt/homebrew/Cellar/perl/5.34.0/lib/perl5/site_perl/5.34.0/darwin-thread-multi-2level/Tk/Derived.pm line 306
>  Tk::Derived::configure at /opt/homebrew/Cellar/perl/5.34.0/lib/perl5/site_perl/5.34.0/darwin-thread-multi-2level/Tk/Derived.pm line 306
>  Tk::Widget::new at /opt/homebrew/Cellar/perl/5.34.0/lib/perl5/site_perl/5.34.0/darwin-thread-multi-2level/Tk/Widget.pm line 205
>  Tk::Widget::__ANON__ at /opt/homebrew/Cellar/perl/5.34.0/lib/perl5/site_perl/5.34.0/darwin-thread-multi-2level/Tk/Widget.pm line 256
>  Tk::DialogWrapper at /opt/homebrew/Cellar/perl/5.34.0/lib/perl5/site_perl/5.34.0/darwin-thread-multi-2level/Tk.pm line 375
>  Tk::FDialog at /opt/homebrew/Cellar/perl/5.34.0/lib/perl5/site_perl/5.34.0/darwin-thread-multi-2level/Tk.pm line 404
>  Tk::__ANON__ at /opt/homebrew/Cellar/perl/5.34.0/lib/perl5/site_perl/5.34.0/darwin-thread-multi-2level/Tk.pm line 272
>  Tk::chooseDirectory at /opt/homebrew/Cellar/perl/5.34.0/lib/perl5/site_perl/5.34.0/darwin-thread-multi-2level/Tk.pm line 353
>  Guiguts::Preferences::locateDirectory at /Users/sharonjoiner/Desktop/guiguts-scannos/src/lib/Guiguts/Preferences.pm line 605
>  Guiguts::Preferences::__ANON__ at /Users/sharonjoiner/Desktop/guiguts-scannos/src/lib/Guiguts/Preferences.pm line 828
>  Tk callback for .toplevel1.frame9.button
>  Tk::__ANON__ at /opt/homebrew/Cellar/perl/5.34.0/lib/perl5/site_perl/5.34.0/darwin-thread-multi-2level/Tk.pm line 251
>  Tk::Button::butUp at /opt/homebrew/Cellar/perl/5.34.0/lib/perl5/site_perl/5.34.0/darwin-thread-multi-2level/Tk/Button.pm line 175
>  <ButtonRelease-1>
>  (command bound to event)

**Comment by windymilla** [comment]
@srjfoo, I haven't changed the code for choosing a scannos folder, just the bit at the start of the program where it detects if the folder chosen previously was under a release, which isn't where you're seeing the error.

However, I don't think you're doing anything wrong - it looks like a genuine bug.

Could you try the same thing in an older release, e.g. 1.4.0 or 1.3.*, please? Just start GG, go to Prefs, File Paths, Set File Paths..., Locate Scannos. It seems to be complaining about the `mustexist` flag, which has been in the code for 18 months. However, it's probably never been run on a Mac, so it's possible the flag hasn't been implemented or can't work on a Mac - the dialog being popped is a directory selection dialog (similar to a file selection dialog) which may well be attempting to use the native dialog rather than a Tk one.

If it fails in the old release as well, I'll just make it so it doesn't specify the `mustexist` flag when running on a Mac, probably under a different PR, since it's unrelated to this change.

You can easily test this PR without the dir selection dialog by manually typing the scannos folder name into the text field to the left of the Locate Scannos button. It defaults to `scannos`, but you should be able to change it to `/Users/sharonjoiner/ggdata/custom-scannos`, then click OK. 
To see whether it has worked (by whatever method you've changed it) you go to Tools, Stealth Scannos and it should pop a file selection dialog in the scannos folder you chose.

Just to clarify, the bug was that if you set it to a name ending in `...scannos`, like your choice, then quit GG and restarted, it would reset the field to the default `scannos`, i.e. the user setting was lost.

Thanks

**Comment by srjfoo** [comment]
> Could you try the same thing in an older release, e.g. 1.4.0 or 1.3.*, please? Just start GG, go to Prefs, File Paths, Set File Paths..., Locate Scannos. It seems to be complaining about the `mustexist` flag, which has been in the code for 18 months. However, it's probably never been run on a Mac, so it's possible the flag hasn't been implemented or can't work on a Mac - the dialog being popped is a directory selection dialog (similar to a file selection dialog) which may well be attempting to use the native dialog rather than a Tk one.
> 
> If it fails in the old release as well, I'll just make it so it doesn't specify the `mustexist` flag when running on a Mac, probably under a different PR, since it's unrelated to this change.

Bingo. It fails on 1.4.0 -- I can go further back if you want, but that was the most convenient release to to a quick test on. Let me know if you want further testing. Here's the error block again, just in case there's anything different in it. (I'll follow your instructions on testing this PR and report back separately.)

> 10:06:32: Guiguts 1.4.0: If you have any problems, please include any error messages that appear here with your bug report.
> 10:07:47: Tk::Error: Can't set -mustexist to `1' for Tk::FBox=HASH(0x12181e288): Can't set -mustexist to `1' for Tk::IconList=HASH(0x1512cefc8): unknown option "-mustexist" at /opt/homebrew/Cellar/perl/5.34.0/lib/perl5/site_perl/5.34.0/darwin-thread-multi-2level/Tk/Configure.pm line 45.
>  at /opt/homebrew/Cellar/perl/5.34.0/lib/perl5/site_perl/5.34.0/darwin-thread-multi-2level/Tk/Derived.pm line 294.
> 
> 
>  at /opt/homebrew/Cellar/perl/5.34.0/lib/perl5/site_perl/5.34.0/darwin-thread-multi-2level/Tk/Derived.pm line 306.
>  Tk callback for .fbox.frame
>  Tk callback for .fbox.frame1
>  Tk callback for .fbox.frame2
>  Tk callback for .fbox
>  Tk callback for .fbox.iconlist
>  Tk::Derived::configure at /opt/homebrew/Cellar/perl/5.34.0/lib/perl5/site_perl/5.34.0/darwin-thread-multi-2level/Tk/Derived.pm line 306
>  Tk::Derived::configure at /opt/homebrew/Cellar/perl/5.34.0/lib/perl5/site_perl/5.34.0/darwin-thread-multi-2level/Tk/Derived.pm line 306
>  Tk::Widget::new at /opt/homebrew/Cellar/perl/5.34.0/lib/perl5/site_perl/5.34.0/darwin-thread-multi-2level/Tk/Widget.pm line 205
>  Tk::Widget::__ANON__ at /opt/homebrew/Cellar/perl/5.34.0/lib/perl5/site_perl/5.34.0/darwin-thread-multi-2level/Tk/Widget.pm line 256
>  Tk::DialogWrapper at /opt/homebrew/Cellar/perl/5.34.0/lib/perl5/site_perl/5.34.0/darwin-thread-multi-2level/Tk.pm line 375
>  Tk::FDialog at /opt/homebrew/Cellar/perl/5.34.0/lib/perl5/site_perl/5.34.0/darwin-thread-multi-2level/Tk.pm line 404
>  Tk::__ANON__ at /opt/homebrew/Cellar/perl/5.34.0/lib/perl5/site_perl/5.34.0/darwin-thread-multi-2level/Tk.pm line 272
>  Tk::chooseDirectory at /opt/homebrew/Cellar/perl/5.34.0/lib/perl5/site_perl/5.34.0/darwin-thread-multi-2level/Tk.pm line 353
>  Guiguts::Preferences::locateDirectory at /Users/sharonjoiner/Desktop/guiguts/lib/Guiguts/Preferences.pm line 601
>  Guiguts::Preferences::__ANON__ at /Users/sharonjoiner/Desktop/guiguts/lib/Guiguts/Preferences.pm line 824
>  Tk callback for .toplevel1.frame9.button
>  Tk::__ANON__ at /opt/homebrew/Cellar/perl/5.34.0/lib/perl5/site_perl/5.34.0/darwin-thread-multi-2level/Tk.pm line 251
>  Tk::Button::butUp at /opt/homebrew/Cellar/perl/5.34.0/lib/perl5/site_perl/5.34.0/darwin-thread-multi-2level/Tk/Button.pm line 175
>  <ButtonRelease-1>
>  (command bound to event)
> 10:07:47: Tk::Error: Can't use an undefined value as a subroutine reference at /opt/homebrew/Cellar/perl/5.34.0/lib/perl5/site_perl/5.34.0/darwin-thread-multi-2level/Tk/FBox.pm line 441.
>  Tk::FBox::__ANON__ at /opt/homebrew/Cellar/perl/5.34.0/lib/perl5/site_perl/5.34.0/darwin-thread-multi-2level/Tk/FBox.pm line 441
>  Tk::FBox::Update at /opt/homebrew/Cellar/perl/5.34.0/lib/perl5/site_perl/5.34.0/darwin-thread-multi-2level/Tk/FBox.pm line 450
>  Tk::After::once at /opt/homebrew/Cellar/perl/5.34.0/lib/perl5/site_perl/5.34.0/darwin-thread-multi-2level/Tk/After.pm line 90
>  [once,[{},after#514,idle,once,[{},Update]]]
>  ("after" script)

**Comment by windymilla** [comment]
Thanks - yes, this PR can progress when you're happy with it. I'll add another for the `mustexist` bug

**Review by srjfoo — APPROVED** [review]
> Just to clarify, the bug was that if you set it to a name ending in ...scannos, like your choice, then quit GG and restarted, it would reset the field to the default scannos, i.e. the user setting was lost.

Yes, once set, the popup worked just fine, and it persisted even after quitting and restarting GG.

**Pull request merged**
