### PR TITLE
Improve LOTE support for Spell Query

### LINKED ISSUE #999: Make Spell Query work without a default dictionary for the language
**Describe the solution you'd like**
There could be no default dictionary under the release, but the user could create a "user" dict in their GGprefs folder. They would then have support for the language. Code change would be to accept the absence of the default as long as there's a user dictionary.

### LINKED ISSUE #1000: Enable Spell Query to support multiple languages
**Describe the solution you'd like**
User would set the language for their text file to "en_la" (English/Latin), having obtained a Latin wordlist from somewhere (Aspell?)
After #999 has been done, they could have it in their GGprefs folder if it's not a language supported by the main GG release.
Code would load en, then la, dictionaries before doing the spell checking.

### LINKED ISSUE #1001: Spell query fails to recognise `l'ami` even if `ami` is in the dictionary
**Describe the bug**
In some (common DP) languages, e.g. French or Italian, a word beginning with a vowel may be preceded by `l'` or `d'`
It would be better if Spell Query re-checked the word, having stripped those from the start.

### PR DESCRIPTION
**Pull request by windymilla**
1. Allow user to put a "user" dictionary (possibly exported from Aspell) in their GGprefs folder, rather than insisting on a "default" dictionary under the release - should make it easier for users to spell check in LOTE. Fixes #999.
2. Support multi-language spell query. Allow language field to contain several language names and just load all the relevant dictionaries. Fixes #1000.
3. Try trimming `l'` and `d'` to support languages that use these, e.g. `l'ami` in French. FIxes #1001.
4. Add Spell Query to test suite.

### CODE REVIEW

**Comment by windymilla** [comment]
Testing notes:
1. Click in status bar to set language, or type in new field in Spell Query dialog, e.g. `en+fr` or `xy zz` or `es`
2. If you set to a language that you have no dict for (e.g. `xy`), it should error when running Spell Query. Then create a file `dict_xy_user.txt` in your GGprefs folder (can contain anything, even be empty). SQ should then run without error.
3. To use multi-languages, just put several languages in the language field, with any delimiter. You do need a dictionary for each language (but can be empty for testing)
4. Previously, a valid word, e.g. `hotel` would fail SQ if written as `l'hotel` (straight or curly apostrophe). Should now succeed
5. To run the full test suite (takes 1 or 2 minutes) run `perl guiguts.pl --runtests`. When it exits, look in the shell window - it will either say how many tests ran (hopefully 76) or something like "Looks as though N tests failed" - scroll back through output to see which tests failed. I don't know if the test suite has been run on a non-Windows computer recently. Note that the testsuite is not included in releases, just dev versions (though I note you can still attempt to run the tests in a release, but obviously they don't succeed!)

**Comment by windymilla** [comment]
@srjfoo, hopefully I've left this in a suitable state for testing. I needed the "Highlight spell queries more accurately" code including so that I could fix the code I'd added to deal with `l'`.

**Comment by cpeel** [comment]
I'd like to hold off reviewing / approving the code until the other PRs are merged in and this PR is updated (and perhaps rebased?). It's a little hard to see what changes are from the description vs what are from other commits.

I'm also rather confused on why the jeebies `README.md` changes are showing up here too. I suspect a merge from head / rebase after the other PRs merge in will fix that.

**Comment by windymilla** [comment]
Sorry @cpeel - I obviously messed something up, trying to get the relevant code into the PR. What I wanted was to have the code from the 2 commits in #995, but for those changes not to show up in this PR. No doubt that's possible, but beyond my limited Git knowledge. 
I'll do as you suggest and wait until the other PRs have been approved and merged, then if things don't resolve with a merge/rebase as you recommend, then, it's trivial to recreate a simplified PR at that point.

**Comment by windymilla** [comment]
Changed my mind - to avoid confusing myself or anyone else, I'll just close this PR and create another when things have caught up.

**Comment by cpeel** [comment]
> No doubt that's possible, but beyond my limited Git knowledge.

You might have been able to do this by rebasing this branch off of the code for #995 and then retargeting this PR to go into that branch and after #995 merged retargeting this to go into `master` again.

In short, it's actually not really possible to easily do what you were hoping in git / Github.

**Comment by windymilla** [comment]
Thanks - definitely simplest for me to start a new PR :)

**Pull request closed without merging**
