### PR TITLE
Prepare for release 1.3.1

### PR DESCRIPTION
**Pull request by windymilla**
Version number and changelog updates

### CODE REVIEW

**Comment by windymilla** [comment]
Feel free to leave this one for a bit - it looks as though there could be a couple more bug fixes to try to squeeze in :)

**Comment by cpeel** [comment]
Will do!

**Comment by cpeel** [comment]
Just an FYI that I'm happy to merge this in whenever you're ready @windymilla -- wanted to make sure you weren't waiting on me.

**Comment by windymilla** [comment]
Thanks - we might as well leave it until I'm ready to make up at least a beta release for the main testers.

**Comment by windymilla** [comment]
@cpeel I'm ready for this to be merged, thank you

**Comment by cpeel** [comment]
Woohoo! Great set of updates!

**Pull request merged**
