### PR TITLE
Generate HTML5 files

### PR DESCRIPTION
**Pull request by windymilla**
HTML autogenerate should create HTML5 files:

1. Always read/write utf8 files
2. Update default HTML header.txt for HTML5 (need to load it as utf8 now)
3. Do not write summary attribute in tables
4. Use numeric, not named, entities apart from a few permitted exceptions
5. Stop pphtml complaining about missing table summary
6. Update test suite to accept numeric emdash entities

### CODE REVIEW

**Comment by windymilla** [comment]
Will do a separate MR after this merge to incorporate the Nu HTML Checker

**Comment by cpeel** [comment]
Looks great! Love seeing all the deleted code 😁 

How do you see these bigger changes as part of the GG release cycle? Are these going into a 1.4 or a 2.0 version? Mostly trying to wrap my head around how (and if) we should be thinking about managing the code with potential 1.3.x updates alongside these bigger changes.

**Comment by windymilla** [comment]
I'm hoping these will be in a 1.4 version, but I'm not envisaging any more 1.3.x updates. I more or less have the changes necessary for the new "Nu" HTML Checker to be bundled and run, in place of the old HTML validator. Once those are in, I can make a test release up for a few eager beavers, then probably a beta release for wider trials of the HTML5 business, then hopefully full release 1.4.0. The changes are really not that huge. It's mostly just a different HTML header at the moment and avoiding named entities.
So, unless you see problems with that scheme, I'd be happy for this to be merged in, and I'll prepare another MR for the Nu HTML Checker.

**Comment by cpeel** [comment]
Sounds like a great plan to me. 👍

**Comment by windymilla** [comment]
Thanks

**Pull request merged**
