### PR TITLE
Remove RST and PGTEI support

### PR DESCRIPTION
**Pull request by windymilla**
Remove menu entries, samples, tools and validation files relating
to RST and PGTEI in Guiguts since no longer used at DP.

### CODE REVIEW

**Comment by cpeel** [comment]
Do we want to remove gnutenberg entirely? If so there are still references to it in `guiguts.pl`, `lib/Guiguts/MenuStructure.pm`, `lib/Guiguts/FileMenu.pm`, `lib/Guiguts/Utilities.pm`, and `run_guiguts.bat`.

For thoroughness we should edit `README.md` in this commit to also remove the comments about RST and PGTEI (which I moved to `INSTALL.md` in my MR and I will adjust there).

**Comment by windymilla** [comment]
Thanks. I'll get another commit sorted with those fixes in

**Comment by windymilla** [comment]
Gnutenberg hopefully removed now. Thanks

**Comment by cpeel** [comment]
I added one more commit to update the README.md and batch file. If that commit looks good to you I'll get this merged in.

**Comment by windymilla** [comment]
Thanks - sorry about not including run_guiguts.bat in my commit. I counted 4 files because I included guiguts.pl - oops. I must improve my procedure - currently have a working release and a local clone of my GitHub repository, which then relies on me copying all the edited files from my working release to my clone, which is where I overlooked run_guiguts.bat. Doing a full directory comparison throws up quite a few differences due to one being an installed version. Mmmm...

**Pull request merged**
